### PR TITLE
bump Cosmos SDK, Tendermint and ibc-go

### PR DESCRIPTION
**Pull request by crodriguezvega**
Bumps Cosmos SDK to 0.44.3, Tendermint to 0.34.14 and ibc-go to v2.0.0.

The main trigger for this PR is that the Cosmos Hub team would like to upgrade to ibc-go 2.0.0 as part of the Vega release. But ibc-go v2.0.0 depends on SDK 0.44.3, so in order to include the packet router in the Vega upgrade we need to bump these dependencies.

This is a draft PR because a couple of changes were needed in the proto files, but when running `make proto-all` I got this error:

```
Formatting Protobuf files
{"path":"proto/router/v1/genesis.proto","start_line":7,"start_column":8,"end_line":7,"end_column":8,"type":"COMPILE","message":"gogoproto/gogo.proto: does not exist"}
{"path":"proto/router/v1/query.proto","start_line":5,"start_column":8,"end_line":5,"end_column":8,"type":"COMPILE","message":"gogoproto/gogo.proto: does not exist"}
make: *** [proto-lint] Error 100
```

@damiannolan helped me with this but also got the same error. He also noticed that we maintain the `third_party/proto` directory in ibc-go but that seems to be missing in this repo.

If somebody (@jackzampolin @jtieri) could help me with the regeneration of the proto files, that would be great. 

And due to the tight timeline for the Vega upgrade, a swift action to merge this PR and release a new version of the packet forward middleware would be very much appreciated. Sorry for the short notice.

cc @yaruwangway

### CODE REVIEW

**Comment by damiannolan** [comment]
I didn't really have the time to dedicate looking into this further, but the summary from my pov is - protobuf linting is failing when running `make proto-all`.
The make targets `proto-gen` and `proto-format` seem to run fine independently, however `proto-lint` fails with the following: 

```
{"path":"proto/router/v1/genesis.proto","start_line":7,"start_column":8,"end_line":7,"end_column":8,"type":"COMPILE","message":"gogoproto/gogo.proto: does not exist"}
{"path":"proto/router/v1/query.proto","start_line":5,"start_column":8,"end_line":5,"end_column":8,"type":"COMPILE","message":"gogoproto/gogo.proto: does not exist"}
```

I figured this was likely due to the absence of `third_party/proto`, but dumping the same directory from ibc-go in here didn't seem to resolve it and that's where I stopped.

**Comment by yaruwangway** [comment]
this error already exits in main branch ?

**Comment by crodriguezvega** [comment]
> this error already exits in main branch ?

Yes, we also try in main branch and we got the same error.

**Review by jackzampolin — APPROVED** [review]

**Comment by jtieri** [comment]
@crodriguezvega I went ahead and pulled your proposed changes into a branch off this repo instead of working off your fork just so we could get package names consistent in one PR (e.g. `option go_package = "github.com/strangelove-ventures/packet-forward-middleware/router/types";`), see #4 

I tried debugging the Protobuf issues where you and Damian left off and the `proto-lint` output was pointing to path issues when attempting to use the Protobuf files in `third_party/proto` directory. I fixed those up but am left with a new set of errors that I have struggled to solve.

**Comment by jackzampolin** [comment]
Hey @crodriguezvega, @jtieri got this working: https://github.com/strangelove-ventures/packet-forward-middleware/pull/4

**Comment by jackzampolin** [comment]
Have this fixed in #4 an released a new point release for you!

https://github.com/strangelove-ventures/packet-forward-middleware/releases/tag/v1.0.1

**Comment by crodriguezvega** [comment]
Great! Thank you so much @jackzampolin and @jtieri!

**Pull request closed without merging**
