### PR TITLE
refactor: Bump Cosmos SDK to v0.46.0-beta2

### PR DESCRIPTION
**Pull request by DavidNix**
See https://github.com/strangelove-ventures/packet-forward-middleware/issues/21 for context.

## IBC Go branch failed

The ibc-go branch, `carlos/upgrade-sdk-0.46-tendermint-0.35` did not work.

```shell
go: finding module for package github.com/cosmos/cosmos-sdk/x/gov/client/rest
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/apps/transfer/types tested by
        github.com/cosmos/ibc-go/v3/modules/apps/transfer/types.test imports
        github.com/tendermint/tendermint/state: module github.com/tendermint/tendermint@latest found (v0.35.4), but does not contain package github.com/tendermint/tendermint/state
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types tested by
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types.test imports
        github.com/cosmos/ibc-go/v3/testing/simapp imports
        github.com/cosmos/cosmos-sdk/x/auth/ante: package github.com/cosmos/cosmos-sdk/x/auth/ante provided by github.com/cosmos/cosmos-sdk at latest version v0.45.4 but not at required version v0.46.0-beta2
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types tested by
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types.test imports
        github.com/cosmos/ibc-go/v3/testing/simapp imports
        github.com/cosmos/cosmos-sdk/x/auth/client/rest: package github.com/cosmos/cosmos-sdk/x/auth/client/rest provided by github.com/cosmos/cosmos-sdk at latest version v0.45.4 but not at required version v0.46.0-beta2
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types tested by
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types.test imports
        github.com/cosmos/ibc-go/v3/testing/simapp imports
        github.com/cosmos/ibc-go/v3/modules/core/02-client/client imports
        github.com/cosmos/cosmos-sdk/types/rest: package github.com/cosmos/cosmos-sdk/types/rest provided by github.com/cosmos/cosmos-sdk at latest version v0.45.4 but not at required version v0.46.0-beta2
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types tested by
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types.test imports
        github.com/cosmos/ibc-go/v3/testing/simapp imports
        github.com/cosmos/ibc-go/v3/modules/core/02-client/client imports
        github.com/cosmos/cosmos-sdk/x/gov/client/rest: package github.com/cosmos/cosmos-sdk/x/gov/client/rest provided by github.com/cosmos/cosmos-sdk at latest version v0.45.4 but not at required version v0.46.0-beta2
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types tested by
        github.com/cosmos/ibc-go/v3/modules/core/04-channel/types.test imports
        github.com/cosmos/ibc-go/v3/testing/simapp imports
        github.com/cosmos/ibc-go/v3/testing/simapp/params imports
        github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx: package github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx provided by github.com/cosmos/cosmos-sdk at latest version v0.45.4 but not at required version v0.46.0-beta2
```

## Fork succeeds with caveats

The fork https://github.com/oopcode/ibc-go/tree/chore/46-beta2 seems to work. 

### Caveats

1. go mod tidy

```shell
# go mod tidy fails unless you run
go mod tidy -compat=1.17  
```

go 1.16 error:

```shell
❯ go mod tidy
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/cosmos-sdk/client imports
        sigs.k8s.io/yaml imports
        gopkg.in/yaml.v2 tested by
        gopkg.in/yaml.v2.test imports
        gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20200902074654-038fdea0a05b,
        but go 1.16 would select v1.0.0-20201130134442-10cb98267c6c
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/cosmos-sdk/types/simulation imports
        github.com/cosmos/cosmos-sdk/crypto/keys/secp256k1 imports
        github.com/btcsuite/btcd/btcec tested by
        github.com/btcsuite/btcd/btcec.test imports
        github.com/btcsuite/btcd/chaincfg/chainhash loaded from github.com/btcsuite/btcd@v0.22.0-beta,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/btcsuite/btcd/chaincfg/chainhash in multiple modules:
        github.com/btcsuite/btcd v0.22.0-beta (/Users/davidnix/go/pkg/mod/github.com/btcsuite/btcd@v0.22.0-beta/chaincfg/chainhash)
        github.com/btcsuite/btcd/chaincfg/chainhash v1.0.0 (/Users/davidnix/go/pkg/mod/github.com/btcsuite/btcd/chaincfg/chainhash@v1.0.0)

To upgrade to the versions selected by go 1.16, leaving some packages unresolved:
        go mod tidy -e -go=1.16 && go mod tidy -e -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
```

2. test warnings

`make test` gives the following warnings.

EDIT: these are macOS specific warnings so may not apply

```shell
❯ make test
go test -mod=readonly -tags='cgo ledger test_ledger_mock'   ./...
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
ok      github.com/strangelove-ventures/packet-forward-middleware/v2/router     (cached)
?       github.com/strangelove-ventures/packet-forward-middleware/v2/router/client/cli  [no test files]
?       github.com/strangelove-ventures/packet-forward-middleware/v2/router/keeper      [no test files]
ok      github.com/strangelove-ventures/packet-forward-middleware/v2/router/parser      (cached)
?       github.com/strangelove-ventures/packet-forward-middleware/v2/router/types       [no test files]
?       github.com/strangelove-ventures/packet-forward-middleware/v2/test       [no test files]
?       github.com/strangelove-ventures/packet-forward-middleware/v2/test/mock  [no test files]
```

### CODE REVIEW

**Comment by DavidNix** [comment]
@okwme fyi

**Comment by DavidNix** [comment]
@crodriguezvega Your branch  `carlos/upgrade-sdk-0.46-tendermint-0.35` worked! 

These produce no errors:

```bash
$ go mod tidy -compat=1.17
$ make test
```

**Comment by DavidNix** [comment]
I cannot upgrade to cosmos-sdk v0.46.0-rc1 because it removes `github.com/cosmos/cosmos-sdk/x/auth/middleware` of which ibc-go uses. The ibc-go branch I'm using `carlos/upgrade-sdk-0.46-tendermint-0.35` does not have any updates as of this writing.

```shell
❯ go mod tidy -compat=1.17
go: finding module for package github.com/cosmos/cosmos-sdk/x/auth/middleware
github.com/strangelove-ventures/packet-forward-middleware/v2/router imports
        github.com/cosmos/ibc-go/v3/modules/apps/transfer/types tested by
        github.com/cosmos/ibc-go/v3/modules/apps/transfer/types.test imports
        github.com/cosmos/ibc-go/v3/testing/simapp imports
        github.com/cosmos/cosmos-sdk/x/auth/middleware: module github.com/cosmos/cosmos-sdk@latest found (v0.45.4), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/middleware
```

Therefore, I think this current branch is our best shot. Moving PR out of draft for review. 

cc @jtieri

**Comment by DavidNix** [comment]
Just to be super clear @jtieri this is ready for your review.

**Review by jtieri — APPROVED** [review]
Looks good, going to merge this now. We can just circle back on the dependancies when there is a clear path forward (i.e. we have a updated branch of ibc-go and a stable release of the SDK 0.46.0). At least his should provide the Gaia team with the means for testing

**Pull request merged**
